---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-backend
  template:
    metadata:
      labels:
        app: chatapp-backend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: chatapp-backend
        image: harbor.pacslab.ca/217847518/chatapp-backend:1.0
        ports:
        - containerPort: 4222
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 400m
            memory: 512Mi
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-frontend
  template:
    metadata:
      labels:
        app: chatapp-frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: chatapp-frontend
        image: harbor.pacslab.ca/217847518/chatapp-frontend:1.0
        ports:
        - containerPort: 30222
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: redis
        image: harbor.pacslab.ca/217847518/redis:7.0.8-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "root"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-frontend
spec:
  type: NodePort
  selector:
    app: chatapp-frontend
  ports:
  - name: http
    port: 80
    targetPort: 30222
    nodePort: 30222
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: tcp
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-backend
spec:
  type: ClusterIP
  selector:
    app: chatapp-backend
  ports:
  - name: tcp
    port: 80
    targetPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432